# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    host_os = RbConfig::CONFIG["host_os"]

    config.vbguest.auto_update = false

    config.vm.box = "win10-msedge"  # https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
    config.vm.guest = "windows"

    # config.vm.network "public_network"

    config.ssh.username = "IEUser"
    config.ssh.password = "Passw0rd!"
    config.ssh.insert_key = false

    vbox_settings = [
        ["--name", "holodeck"],
        ["--memory", 4096],
        ["--cpus", 2],
        ["--vram", 128],
        ["--audio", host_os.include?("darwin") ? "coreaudio" : host_os.include?("linux") ? "pulse" : "dsound"],
        ["--audiocontroller", "hda"],
        ["--clipboard", "bidirectional"],
        ["--macaddress1", "auto"]
    ]

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = true
        vbox.linked_clone = true

        vbox_settings.each do |setting, value|
            vbox.customize ["modifyvm", :id, setting, value]
        end
    end

    config.vm.provision "file", source: "provision.ps1", destination: "C:/Users/IEUser/Desktop/RUN AS ADMIN.ps1"

end
