# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../settings"


Vagrant.configure("2") do |config|

    config.vbguest.auto_update = false

    config.vm.box = "win10-msedge-20170320"  # https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
    config.vm.guest = "windows"

    # config.vm.network "public_network"

    config.ssh.username = "IEUser"
    config.ssh.password = "Passw0rd!"
    config.ssh.insert_key = false

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = true
        vbox.linked_clone = true

        Settings::VBOX.each do |setting, value|
            vbox.customize ["modifyvm", :id, setting, value]
        end
    end

    guest_additions_iso = [
        "/Applications/VirtualBox.app",
        "C:/Program Files/Oracle/VirtualBox"
    ].map{ |vbox_dir| Dir.glob("#{vbox_dir}/**/VBoxGuestAdditions.iso") }.flatten.pop

    home = "C:/Users/IEUser"

    config.vm.provision "file", source: guest_additions_iso, destination: "#{home}/Downloads/VBoxGuestAdditions.iso"
    config.vm.provision "file", source: "provision.ps1", destination: "#{home}/Desktop/RUN AS ADMIN.ps1"
    config.vm.provision "file", source: "powershell.lnk", destination: "#{home}/Desktop/Windows PowerShell.lnk"

end
