# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "jhcook/macos-sierra"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        [
            ["--memory", 4096],
            ["--cpus", 2]
        ].each do |setting, value|
            vb.customize ["modifyvm", :id, setting, value]
        end
    end

    # config.vm.provider "vmware_fusion" do |vmware|
    #     # many of the parameters for vmware fusion are undocumented so you'll need to look in the .vmx file and experiment
    #     # ref: https://thornelabs.net/2013/09/28/customizing-vagrant-vmware-fusion-virtual-machines-with-vmx-parameters.html
    #     vmware.gui = true
    #     [
    #         ["memsize", 4096],
    #         ["numvcpus", 2]
    #     ].each do |setting, value|
    #         vmware.vmx[setting] = value
    #     end
    # end

    Dir.glob("run_once/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, privileged: false
    end

    Dir.glob("run_always/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, privileged: false, run: "always"
    end

end
