# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../settings"


Vagrant.configure("2") do |config|

    config.vm.box = "jhcook/macos-sierra"  # this box only works with virtualbox
    config.vm.guest = "darwin"
    config.vm.hostname = Settings::NAME

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = true
        vbox.linked_clone = true

        Settings::VBOX.each do |setting, value|
            vbox.customize ["modifyvm", :id, setting, value]
        end
    end

    # config.vm.provider "vmware_fusion" do |vmware|
    #     vmware.gui = true

    #     Settings::VMWARE.each do |setting, value|
    #         vmware.vmx[setting] = value
    #     end
    # end

    # config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    # config.vm.network "public_network"

    # config.vm.synced_folder "source", "dest"

    Dir.glob("run_once/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false
    end

    Dir.glob("run_always/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false, run: "always"
    end

    config.vm.post_up_message = <<~MSG
        - Just provisioned? `vagrant reload` recommended
        - Username/Password: vagrant/vagrant
    MSG

end
