# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative "../settings"


Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"
    config.vm.hostname = Settings::NAME

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.linked_clone = true

        Settings::VBOX.each do |setting, value|
            vbox.customize ["modifyvm", :id, setting, value]
        end

        disk = ".vagrant/custom-hdd.vdi"
        capacity = 100 * 1024  # megabytes
        vbox.customize ["createmedium", "disk", "--filename", disk, "--size", capacity] unless File.exists? disk
        vbox.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 2, "--device", 0, "--type", "hdd", "--medium", disk]
    end

    # config.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    # config.vm.network "public_network"

    # config.vm.synced_folder "source", "dest"

    Dir.glob("run_once/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false
    end

    Dir.glob("run_always/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false, run: "always"
    end

    config.vm.post_up_message = <<~MSG
        - Just provisioned? `vagrant reload` recommended
    MSG

end
