# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "ubuntu/xenial64"

    # config.vm.network "public_network"

    vbox_settings = [
        ["--name", "holodeck"],
        ["--memory", 4096],
        ["--cpus", 2],
        ["--vram", 64]
    ]

    config.vm.provider "virtualbox" do |vbox|
        vbox.gui = false
        vbox.linked_clone = true

        vbox_settings.each do |setting, value|
            vbox.customize ["modifyvm", :id, setting, value]
        end

        disk = ".vagrant/extra-hdd.vdi"
        capacity = 100 * 1024  # megabytes
        vbox.customize ["createmedium", "disk", "--filename", disk, "--size", capacity] unless File.exists? disk
        vbox.customize ["storageattach", :id, "--storagectl", "SCSI", "--port", 2, "--device", 0, "--type", "hdd", "--medium", disk]
    end

    config.vm.provision "docker"

    Dir.glob("run_once/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false
    end

    Dir.glob("run_always/*.sh").sort.each do |script|
        config.vm.provision "shell", path: script, name: script, privileged: false, run: "always"
    end

end
